config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  authenticated :user do
    root to: "groups#index"
  end

  unauthenticated do
    root to: 'application#main', as: :unauth_root
  end

  authenticate :user do
    get '/groups/class_edit', to: "groups#class_edit", as: 'class_edit'
    resources :groups do
      resources :separations, only: [:create, :destroy]
      get 'students/roster_edit', to: "students#roster_edit", as: "edit_roster"
      resources :students, except: [:index, :show, :edit]
    end
    get '/groups/:id/small_groups', to: "groups#small_groups", as: "small_groups"
    put '/groups/:id/gender_setter', to: "groups#gender_setter"
    get '/groups/:id/class_settings', to: "groups#class_settings", as: "class_settings"
    post '/groups/:id/grouping', to: "groups#grouping"
  end

end

app/models/student.rb
class Student < ActiveRecord::Base
  belongs_to :group
  validates :first_name, :last_name, :gender, :group, presence: true

  def full_name
    "#{first_name} #{last_name}"
  end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_group
  before_action :set_student, only: [:update, :destroy]
  before_action :authenticate_user!

  def new
    @student = Student.new
  end

  def create
    @student = @group.students.build(student_params)
    if @student.save
      flash[:notice] = 'Student created, next...'
      redirect_to new_group_student_path
    else
      flash[:alert] = 'Student was not created'
      render 'new'
    end
  end

  def roster_edit
  end

  def update
    if @student.update(student_params)
      flash[:notice] = "#{@student.first_name} #{@student.last_name} updated."
      redirect_to group_edit_roster_path(@group)
    else
      flash[:alert] = "Unable to update"
      render action: 'roster_edit'
    end
  end

  def destroy
    @group.separations.each do |separt|
      if separt.person1_id == @student.id || separt.person2_id == @student.id
        separt.destroy
      end
    end
    @student.destroy
    flash[:alert] = "#{@student.first_name} #{@student.last_name} has been removed from your roster."
    redirect_to group_edit_roster_path(@group)
  end

  private

    def student_params
      params.require(:student).permit(:first_name, :last_name, :gender)
    end

    def set_group
      @group = Group.find(params[:group_id])
    rescue ActiveRecord::RecordNotFound
      flash[:alert] = 'The class your looking for could not be found.'
      redirect_to root_path
    end

    def set_student
      @student = @group.students.find(params[:id])
    end

end

app/views/students/_form.html.erb
<%= form_for [@group, @student] do |f| %>

  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %>
        prohibited this student from being saved:</h2>
      <ul>
      <% @student.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </p>

  <p>
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </p>

  <p>
    <%= f.label :gender %><br>
    Female: <%= f.radio_button :gender, "female" %><br>
    Male: <%= f.radio_button :gender, "male" %>
  </p>

  <%= f.submit "Add student", class: "btn btn-success" %>
  <%= link_to "#{@group.title}'s Roster", group_path(@group), class: "btn btn-default" %>
<% end %>

app/views/students/new.html.erb
<h1><%= @group.title %></h1>
<div class="row">
  <div class="col-sm-7">
    <h2>Add student:</h2>

    <%= render 'form' %>

  </div>

  <div class="col-sm-5">
    <h3>Current roster:</h3>

    <% @group.alpha_students.each do |student| %>
      <li><%= student.last_name %>, <%= student.first_name %></li>
    <% end %>
  </div>
</div>

app/views/students/roster_edit.html.erb
<h3>Class Roster</h3>

<%= link_to "Add more students", new_group_student_path(@group) %> |
<%= link_to "Class settings", class_settings_path(@group) %> |
<%= link_to "Back to #{@group.title}", group_path(@group) %>

<div class="row">
  <div style="width:60%" class="table">
    <% @group.alpha_students.each do |student| %>
      <div class="tr">
        <%= form_for [@group, student] do |f| %>
          <span class="td"><%= f.label "First" %><%= f.text_field :first_name %></span>
          <span class="td"><%= f.label "Last" %><%= f.text_field :last_name %></span>
          <span class="td"><%= f.label "M" %><%= f.radio_button :gender, 'male' %></span>
          <span class="td"><%= f.label "F" %><%= f.radio_button :gender, 'female' %></span>
          <span class="td"><%= f.submit "Save Change", class: "btn btn-success btn-sm roster-margin" %></span>
        <% end %>
        <span class="td"><%= button_to "Remove #{student.first_name}", group_student_path(@group, student), class: "btn btn-primary btn-sm roster-margin", method: :delete %></span>
      </div>
    <% end %>
  </div>
</div>