config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  authenticated :user do
    root to: "groups#index"
  end

  unauthenticated do
    root to: 'application#main', as: :unauth_root
  end

  authenticate :user do
    get '/groups/class_edit', to: "groups#class_edit", as: 'class_edit'
    resources :groups do
      resources :separations, only: [:create, :destroy]
      get 'students/roster_edit', to: "students#roster_edit", as: "edit_roster"
      resources :students, except: [:index, :show, :edit]
    end
    get '/groups/:id/small_groups', to: "groups#small_groups", as: "small_groups"
    put '/groups/:id/gender_setter', to: "groups#gender_setter"
    get '/groups/:id/class_settings', to: "groups#class_settings", as: "class_settings"
    post '/groups/:id/grouping', to: "groups#grouping"
  end

end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :students, dependent: :delete_all
  has_many :separations, dependent: :delete_all
  belongs_to :user

  validates :title, :user, presence: true

  def check_loop_scenario
    return false unless separations.size == 3
    used_ids = []
    separations.each do |separt|
      used_ids << separt.person1_id
      used_ids << separt.person2_id
    end
    used_ids.uniq.size == 3
  end

  def alpha_students
    students.sort { |a,b| a.last_name.downcase <=> b.last_name.downcase }
  end

  def girls
    students.select { |student| "female" == student.gender }
  end

  def boys
    students.select { |student| "male" == student.gender }
  end

  def minority
    boys.length < girls.size ? boys : girls
  end

  def majority
    boys.length >= girls.size ? boys : girls
  end

  def separation_detector
    separations != []
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :update, :destroy, :small_groups, :grouping, :class_settings, :gender_setter]
  before_action :authenticate_user!

  def index
  end

  def show
  end

  def new
    @group = Group.new
  end

  def create
    @group = current_user.groups.build(group_params)
    if @group.save
      redirect_to new_group_student_path(@group)
    else
      flash[:alert] = "Class needs to have a title"
      render "new"
    end
  end

  def class_edit
  end

  def update
    if @group.update(group_params)
      flash[:notice] = "#{@group.title} updated."
      redirect_to :class_edit
    else
      flash[:alert] = "Unable to update"
      render action: 'class_edit'
    end
  end

  def destroy
    @group.destroy
    flash[:alert] = "#{@group.title} has been deleted."
    redirect_to groups_path
  end

  def gender_setter
    @group.update(group_params)
    redirect_to :class_settings
  end

  def small_groups
    @group.check_loop_scenario ? @min = 3 : @min = 2
    @max = ((@group.students.size + 1) / 2) > 2 ? ((@group.students.size + 1) / 2) : 2
  end

  def grouping
    if @group.students.size < 5
      flash[:alert] = "Must have at least 5 students in class to create random groups. Please add students to roster."
      redirect_to :small_groups and return
    end
    number = "" == params[:number] ? "3" : params[:number]
    sorted_groups = Separator.new(Subgroup.new(number, @group))
    @final_groups = SubgroupFormatter.new(sorted_groups).html
    @group.check_loop_scenario ? @min = 3 : @min = 2
    @max = ((@group.students.size + 1) / 2) > 2 ? ((@group.students.size + 1) / 2) : 2
    render :small_groups
  end

  def class_settings
  end

  private

    def set_group
      @group = Group.find(params[:id])
    end

    def group_params
      params.require(:group).permit(:title, :genderfied)
    end

end

app/views/groups/class_edit.html.erb
<h2>All your classes</h2>
<div class="row">
  <div style="width:50%" class="table">
    <% current_user.groups.each do |group| %>
      <div class="tr">
        <%= form_for (group) do |f| %>
          <span class="td"><%= f.text_field :title %></span>
          <span class="td"><%= f.submit "Save Change" %></span>
        <% end %>
          <span class="td"><%= button_to "Remove #{group.title}", group_path(group), method: :delete, data: { confirm: "Are you sure you want to delete this class for good?" } %></span>
      </div>
    <% end %>
  </div>
</div>

<%= link_to "Back", groups_path %>

app/views/groups/class_settings.html.erb
<h2>Class Settings</h2>

<p><strong>On this page you can set parameters for this group's randomization. These extra filters will NOT be displayed on any other page.</strong></p>

<p>With this button checked, every randomization will create mixed gender groups. If your roster does not contain enough girls or boys for every group to be mixed, the program will spread out the minority gender as much as possible. This feature defaults to mixed, as studies show that mixed gender groups are better.</p>

<%= form_for :group, url: "/groups/#{@group.id}/gender_setter", method: :put do |f| %>
  <%= f.label :genderfied, "Gender Mixed:" %>
  <%= f.check_box "genderfied" %>
  <%= f.hidden_field "title" %>
  <%= f.submit 'Save selection' %>
<% end %>

<P>You may also set pairs of students that should never be grouped together. Whether these students don't get along, or they goof off so much that your classroom environment suffers, this option will keep the randomizer from ever putting them in the same group.</p>

<%= form_for :separation, url: "/groups/#{@group.id}/separations", method: :post do |f| %>
  <%= f.label "Student 1:" %>
  <%= f.select :person1_id, @group.alpha_students.collect { |student| [ "#{student.first_name} #{student.last_name}", student.id ] } %>
  <%= f.label "Student 2:" %>
  <%= f.select :person2_id, @group.alpha_students.collect { |student| [ "#{student.first_name} #{student.last_name}", student.id ] } %>
  <%= f.submit "Keep these two separate" %>
<% end %>

<% if @group.separations.size != 0 %>
  <h5>Current separated students: (3 cases maximum)</h5>
  <% @group.separations.each do |separt| %>
    <%= separt.id1_to_name %> will not be grouped with <%= separt.id2_to_name %> - <%= link_to "Remove Separation", group_separation_path(@group, separt), method: :delete, data: { confirm: "Are you sure you want to erase this clause?" } %><br>
  <% end %>
<% end %>

<div class="navbar-text">
  <%= link_to "Back", @group %>
</div>

app/views/groups/index.html.erb
<h2>Select a Class</h2>

<%= link_to "Add Class", new_group_path %> |
<%= link_to "Edit or Delete class", :class_edit %><br><br>

<% if current_user.groups.first == nil %>
  <p>No classes created yet. <%= link_to "Click here to get started.", new_group_path %></p>
<% else %>
  <% current_user.groups.each do |group| %>
    <%= link_to group.title, group, class: "btn btn-info class-button" %><br>
  <% end %>
<% end %>

app/views/groups/new.html.erb
<%= form_for(@group) do |f| %>

  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %>
        prohibited this group from being saved:</h2>
      <ul>
      <% @group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title, "Class title" %><br>
    <%= f.text_field :title %>
  </p>
  <%= f.hidden_field :genderfied, value: "1" %>
  <%= f.submit "Create Class", class: "btn btn-success" %>

<% end %><br>

<%= link_to "Back", groups_path %>

app/views/groups/show.html.erb
<h2><%= @group.title %></h2>

<%= link_to "Create random groups", :small_groups %> | 
<%= link_to "Edit roster", group_edit_roster_path(@group) %> | 
<%= link_to "Class settings", :class_settings %> | 
<%= link_to "Back", groups_path %>

<h3>Class Roster</h3>
<ul>
  <% @group.alpha_students.each do |student| %>
    <li><%= student.last_name %>, <%= student.first_name %></li>
  <% end %>
</ul>

app/views/groups/small_groups.html.erb
<h2>Random Groups for <%= @group.title %></h2>

<%= link_to "Back", group_path %>

<div class="col-xs-12 text-center">
  <%= form_tag("/groups/#{@group.id}/grouping") do %>
    <%= label_tag 'Number of groups' %>
    <%= number_field_tag 'number', nil, min: @min, max: @max, class: "group-number" %>
    <%= submit_tag 'Create Random Groups', class: "btn btn-sm btn-info" %>
  <% end %>
</div>

<% if @final_groups %>
  <%= @final_groups %>
<% end %>