config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  authenticated :user do
    root to: "groups#index"
  end

  unauthenticated do
    root to: 'application#main', as: :unauth_root
  end

  authenticate :user do
    get '/groups/class_edit', to: "groups#class_edit", as: 'class_edit'
    resources :groups do
      resources :separations, only: [:create, :destroy]
      get 'students/roster_edit', to: "students#roster_edit", as: "edit_roster"
      resources :students, except: [:index, :show, :edit]
    end
    get '/groups/:id/small_groups', to: "groups#small_groups", as: "small_groups"
    put '/groups/:id/gender_setter', to: "groups#gender_setter"
    get '/groups/:id/class_settings', to: "groups#class_settings", as: "class_settings"
    post '/groups/:id/grouping', to: "groups#grouping"
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CustomGroups</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <div class="navbar-text pull-right">
      <% if user_signed_in? %>
        Logged in as <strong><%= current_user.username %></strong>.
        <%= link_to 'Home', groups_path, class: 'navbar-link' %> |
        <%= link_to 'Edit profile', edit_user_registration_path, class: 'navbar-link' %> |
        <%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'navbar-link'  %>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path, class: 'navbar-link'  %> |
        <%= link_to "Login", new_user_session_path, class: 'navbar-link'  %>
      <% end %>
    </div>

    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <div class="container"></div>

    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>